x-defaults: &defaults
  restart: ${RESTART_POLICY:-unless-stopped}
  env_file:
    - "./.env"
  volumes:
    - /etc/timezone:/etc/timezone:ro
    - /etc/localtime:/etc/localtime:ro
  networks:
    - huly-internal-net
  logging:
    driver: ${LOGGING_DRIVER:-json-file}
    options:
      max-size: ${LOGGING_MAX_SIZE:-10m}
      max-file: ${LOGGING_MAX_FILE:-3}
  security_opt:
    - no-new-privileges:true # restrict privileges, to prevent privilege escalation

services:
  huly-mongodb:
    image: mongo:${MONGODB_IMAGE_TAG:-7-jammy}
    container_name: ${MONGODB_CONTAINER_NAME:-huly-mongodb}
    hostname: ${MONGODB_HOSTNAME:-huly-mongodb}
    <<: [*defaults]
    healthcheck:
      test: [
        "CMD",
        "mongosh", "--eval", "'(db.runCommand({ ping: 1 }).ok ? 0 : 1)'"
      ]
      interval: ${MONGODB_HEALTHCHECK_INTERVAL:-10s}
      timeout: ${MONGODB_HEALTHCHECK_TIMEOUT:-10s}
      retries: ${MONGODB_HEALTHCHECK_RETRIES:-5}
      start_period: ${MONGODB_HEALTHCHECK_START_PERIOD:-30s}
    volumes:
      - ${MONGODB_DATA_PATH:-?}:/data/db
      - ${MONGODB_CONF_PATH:-?}:/data/configdb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME:-huly}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD:?}

  huly-elastic:
    image: elasticsearch:${ELASTIC_IMAGE_TAG:-7.14.2}
    container_name: ${ELASTIC_CONTAINER_NAME:-huly-elastic}
    hostname: ${ELASTIC_HOSTNAME:-huly-elastic}
    <<: [*defaults]
    healthcheck:
      # status:
      #   red: share is not allocated
      #   yellow: primary shard is allocated but replicas are not
      #   green. all shards are allocated
      test: [
        "CMD-SHELL",
        "curl --silent http://localhost:9200/_cluster/health | grep --quiet --invert-match '\"status\":\"red\"'"
      ]
      interval: ${ELASTIC_HEALTHCHECK_INTERVAL:-20s}
      timeout: ${ELASTIC_HEALTHCHECK_TIMEOUT:-10s}
      retries: ${ELASTIC_HEALTHCHECK_RETRIES:-5}
      start_period: ${ELASTIC_HEALTHCHECK_START_PERIOD:-30s}
    volumes:
      - ${ELASTIC_CONF_PATH:?}:/usr/share/elasticsearch/config
      - ${ELASTIC_DATA_PATH:?}:/usr/share/elasticsearch/data
      - ${ELASTIC_LOGS_PATH:?}:/usr/share/elasticsearch/logs
    environment:
      - ELASTICSEARCH_PORT_NUMBER=${ELASTIC_PORT:-9200}
      - discovery.type=${ELASTIC_DISCOVERY_TYPE:-single-node}
      - ES_JAVA_OPTS=${ELASTIC_JAVA_OPTS:--Xms4096m -Xmx4096m}
      - bootstrap.memory_lock=${ELASTIC_MEMORY_LOCK:-true} # disallow using swap storage
    ulimits:
      memlock:
        soft: -1
        hard: -1
    # check if "ingest-attachment" plugin is installed, if not install it
    # after that, execute this script: https://github.com/elastic/elasticsearch/blob/main/distribution/docker/src/docker/bin/docker-entrypoint.sh
    command: |
      /bin/sh -c "./bin/elasticsearch-plugin list | grep --quiet ingest-attachment ||
                  yes | ./bin/elasticsearch-plugin install --silent ingest-attachment;
                  /usr/local/bin/docker-entrypoint.sh eswrapper"
    sysctls:
      - vm.max_map_count=${ELASTIC_VM_MAX_MAP_COUNT:-262144}

  huly-minio:
    image: minio/minio:${MINIO_IMAGE_TAG:-RELEASE.2024-10-13T13-34-11Z}
    container_name: ${MINIO_CONTAINER_NAME:-huly-minio}
    hostname: ${MINIO_HOSTNAME:-huly-minio}
    <<: [*defaults]
    volumes:
      - ${MINIO_DATA_PATH:?}:/data
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER:-huly}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:?}
    command: "server /data --address \":9000\""

  huly-rekoni:
    image: hardcoreeng/rekoni-service:${HULY_IMAGE_TAG:-v0.6.337}
    container_name: ${REKONI_CONTAINER_NAME:-huly-rekoni}
    hostname: ${REKONI_HOSTNAME:-huly-rekoni}
    <<: [*defaults]
    environment:
      - SECRET=${HULY_SECRET:?}
    networks:
      - huly-internal-net
      - huly-public-net

  huly-transactor:
    image: hardcoreeng/transactor:${HULY_IMAGE_TAG:-v0.6.337}
    container_name: ${TRANSACTOR_CONTAINER_NAME:-huly-transactor}
    hostname: ${TRANSACTOR_HOSTNAME:-huly-transactor}
    <<: [*defaults]
    volumes:
      - ${TRANSACTOR_LOGS_PATH:?}:/usr/src/app/logs
    environment:
      - SERVER_PORT=${TRANSACTOR_PORT:-3333}
      - SERVER_SECRET=${HULY_SECRET:?}
      - SERVER_CURSOR_MAXTIMEMS=${TRANSACTOR_SERVER_CURSOR_MAXTIMEMS:-30000}
      - ELASTIC_URL=${ELASTIC_URL:-http://${ELASTIC_HOSTNAME:-huly-elastic}:${ELASTIC_PORT:-9200}}
      - ELASTIC_INDEX_NAME=${ELASTIC_INDEX_NAME:-huly_storage_index}
      - MONGO_URL=${MONGODB_URL:-mongodb://${MONGODB_USERNAME:-huly}:${MONGODB_PASSWORD:?}@${MONGODB_HOSTNAME:-huly-mongodb}:${MONGODB_PORT:-27017}}
      - METRICS_CONSOLE=${TRANSACTOR_METRICS_CONSOLE:-false}
      - METRICS_FILE=${TRANSACTOR_METRICS_FILE:-metrics.txt}
      - STORAGE_CONFIG=${STORAGE_CONFIG:-minio|${MINIO_HOSTNAME:-huly-minio}?accessKey=${MINIO_ROOT_USER:-huly}&secretKey=${MINIO_ROOT_PASSWORD:-?}}
      - REKONI_URL=${REKONI_URL:-http://${REKONI_HOSTNAME:-huly-rekoni}:${REKONI_PORT:-4004}}
      - FRONT_URL=${FRONT_URL:-http://${FRONT_HOSTNAME:-huly-front}:${FRONT_PORT:-8080}}
      - ACCOUNTS_URL=${ACCOUNT_URL:-http://${ACCOUNT_HOSTNAME:-huly-hostname}:${ACCOUNT_PORT:-3000}}
      - LAST_NAME_FIRST=${HULY_CONFIG_LAST_NAME_FIRST:-true}
      - UPLOAD_URL=${TRANSACTOR_UPLOAD_URL:-${HTTP_SCHEME:-http}://${SERVER_ADDRESS:?}/files}
    networks:
      - huly-internal-net
      - huly-public-net

  huly-collaborator:
    image: hardcoreeng/collaborator:${HULY_IMAGE_TAG:-v0.6.337}
    container_name: ${COLLABORATOR_CONTAINER_NAME:-huly-collaborator}
    hostname: ${COLLABORATOR_HOSTNAME:-huly-collaborator}
    <<: [*defaults]
    volumes:
      - ${COLLABORATOR_LOGS_PATH:?}:/usr/src/app/logs
    environment:
      - COLLABORATOR_PORT=${COLLABORATOR_PORT:-3078}
      - SECRET=${HULY_SECRET:?}
      - ACCOUNTS_URL=${ACCOUNT_URL:-http://${ACCOUNT_HOSTNAME:-huly-hostname}:${ACCOUNT_PORT:-3000}}
      - MONGO_URL=${MONGODB_URL:-mongodb://${MONGODB_USERNAME:-huly}:${MONGODB_PASSWORD:?}@${MONGODB_HOSTNAME:-huly-mongodb}:${MONGODB_PORT:-27017}}
      - STORAGE_CONFIG=${STORAGE_CONFIG:-minio|${MINIO_HOSTNAME:-huly-minio}?accessKey=${MINIO_ROOT_USER:-huly}&secretKey=${MINIO_ROOT_PASSWORD:-?}}
    networks:
      - huly-internal-net
      - huly-public-net

  huly-account:
    image: hardcoreeng/account:${HULY_IMAGE_TAG:-v0.6.337}
    container_name: ${ACCOUNT_CONTAINER_NAME:-huly-account}
    hostname: ${ACCOUNT_HOSTNAME:-huly-account}
    <<: [*defaults]
    volumes:
      - ${ACCOUNT_LOGS_PATH:?}:/usr/src/app/logs
    environment:
      - SERVER_PORT=${ACCOUNT_PORT:-3000}
      - SERVER_SECRET=${HULY_SECRET:?}
      - MONGO_URL=${MONGODB_URL:-mongodb://${MONGODB_USERNAME:-huly}:${MONGODB_PASSWORD:?}@${MONGODB_HOSTNAME:-huly-mongodb}:${MONGODB_PORT:-27017}}
      - TRANSACTOR_URL=${TRANSACTOR_URL:-ws://${TRANSACTOR_HOSTNAME:-huly-transactor}:${TRANSACTOR_PORT:-3333};${WS_SCHEME}://${SERVER_ADDRESS:?}/_transactor}
      - STORAGE_CONFIG=${STORAGE_CONFIG:-minio|${MINIO_HOSTNAME:-huly-minio}?accessKey=${MINIO_ROOT_USER:-huly}&secretKey=${MINIO_ROOT_PASSWORD:-?}}
      - FRONT_URL=${FRONT_URL:-http://${FRONT_HOSTNAME:-huly-front}:${FRONT_PORT:-8080}}
      - MODEL_ENABLED=${ACCOUNT_MODEL_ENABLED:-*}
      - ACCOUNT_PORT=${ACCOUNT_PORT:-3000}
      - ACCOUNTS_URL=${ACCOUNT_URL:-http://${ACCOUNT_HOSTNAME:-huly-hostname}:${ACCOUNT_PORT:-3000}}
    networks:
      - huly-internal-net
      - huly-public-net

  huly-workspace:
    image: hardcoreeng/workspace:${HULY_IMAGE_TAG:-v0.6.337}
    container_name: ${WORKSPACE_CONTAINER_NAME:-huly-workspace}
    hostname: ${WORKSPACE_HOSTNAME:-huly-workspace}
    <<: [*defaults]
    volumes:
      - ${WORKSPACE_LOGS_PATH:?}:/usr/src/app/logs
    environment:
      - SERVER_SECRET=${HULY_SECRET:?}
      - MONGO_URL=${MONGODB_URL:-mongodb://${MONGODB_USERNAME:-huly}:${MONGODB_PASSWORD:?}@${MONGODB_HOSTNAME:-huly-mongodb}:${MONGODB_PORT:-27017}}
      - TRANSACTOR_URL=${TRANSACTOR_URL:-ws://${TRANSACTOR_HOSTNAME:-huly-transactor}:${TRANSACTOR_PORT:-3333};${WS_SCHEME}://${SERVER_ADDRESS:?}/_transactor}
      - STORAGE_CONFIG=${STORAGE_CONFIG:-minio|${MINIO_HOSTNAME:-huly-minio}?accessKey=${MINIO_ROOT_USER:-huly}&secretKey=${MINIO_ROOT_PASSWORD:-?}}
      - MODEL_ENABLED=${WORKSPACE_MODEL_ENABLED:-*}
      - ACCOUNTS_URL=${ACCOUNT_URL:-http://${ACCOUNT_HOSTNAME:-huly-hostname}:${ACCOUNT_PORT:-3000}}
      - NOTIFY_INBOX_ONLY=${HULY_CONFIG_NOTIFY_INBOX_ONLY:-true}
    networks:
      - huly-internal-net
      - huly-public-net

  huly-front:
    image: hardcoreeng/front:${HULY_IMAGE_TAG:-v0.6.337}
    container_name: ${FRONT_CONTAINER_NAME:-huly-front}
    hostname: ${FRONT_HOSTNAME:-huly-front}
    <<: [*defaults]
    volumes:
      - ${FRONT_LOGS_PATH:?}:/app/logs
    environment:
      - SERVER_PORT=${FRONT_PORT:-8080}
      - SERVER_SECRET=${HULY_SECRET:?}
      - ACCOUNTS_URL=${PUBLIC_ACCOUNTS_URL:-${HTTP_SCHEME:-http}://${SERVER_ADDRESS:?}/_accounts}
      - REKONI_URL=${PUBLIC_REKONI_URL:-${HTTP_SCHEME:-http}://${SERVER_ADDRESS:?}/_rekoni}
      - CALENDAR_URL=${PUBLIC_CALENDAR_URL:-${HTTP_SCHEME:-http}://${SERVER_ADDRESS:?}/_calendar}
      - GMAIL_URL=${PUBLIC_GMAIL_URL:-${HTTP_SCHEME:-http}://${SERVER_ADDRESS:?}/_gmail}
      - TELEGRAM_URL=${PUBLIC_TELEGRAM_URL:-${HTTP_SCHEME:-http}://${SERVER_ADDRESS:?}/_telegram}
      - COLLABORATOR_URL=${PUBLIC_COLLABORATOR_URL:-${HTTP_SCHEME:-http}://${SERVER_ADDRESS:?}/_collaborator}
      - UPLOAD_URL=${FRONT_UPLOAD_URL:-/files}
      - ELASTIC_URL=${ELASTIC_URL:-http://${ELASTIC_HOSTNAME:-huly-elastic}:${ELASTIC_PORT:-9200}}
      - STORAGE_CONFIG=${STORAGE_CONFIG:-minio|${MINIO_HOSTNAME:-huly-minio}?accessKey=${MINIO_ROOT_USER:-huly}&secretKey=${MINIO_ROOT_PASSWORD:-?}}
      - MONGO_URL=${MONGODB_URL:-mongodb://${MONGODB_USERNAME:-huly}:${MONGODB_PASSWORD:?}@${MONGODB_HOSTNAME:-huly-mongodb}:${MONGODB_PORT:-27017}}
      - TITLE=${HULY_CONFIG_TITLE:-Huly Self Host}
      - DEFAULT_LANGUAGE=${HULY_CONFIG_DEFAULT_LANGUAGE:-en}
      - LAST_NAME_FIRST=${HULY_CONFIG_LAST_NAME_FIRST:-true}
    networks:
      - huly-internal-net
      - huly-public-net

  huly-nginx:
    image: nginx:${NGINX_IMAGE_TAG:-1.21.3}
    container_name: ${NGINX_CONTAINER_NAME:-huly-nginx}
    hostname: ${NGINX_HOSTNAME:-huly-nginx}
    <<: [*defaults]
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost" ]
      interval: ${NGINX_HEALTHCHECK_INTERVAL:-30s}
      timeout: ${NGINX_HEALTHCHECK_TIMEOUT:-5s}
      retries: ${NGINX_HEALTHCHECK_RETRIES:-3}
      start_period: ${NGINX_HEALTHCHECK_START_PERIOD:-10s}
    volumes:
      - ${NGINX_CONF_PATH:?}:/etc/nginx/conf.d
    ports:
      - ${NGINX_PORT:-80}:80
    networks:
      - huly-internal-net
      - huly-public-net

networks:
  huly-public-net:
    name: ${PUBLIC_NET:-huly-public-net}
    driver: bridge
  huly-internal-net:
    name: ${INTERNAL_NET:-huly-internal-net}
    driver: bridge
    internal: true

volumes:
  mongodb-data:
    name: ${MONGODB_DATA_NAME:-huly-mongodb-data}
  mongodb-conf:
    name: ${MONGODB_CONF_NAME:-huly-mongodb-conf}
  elastic-logs:
    name: ${ELASTIC_LOGS_NAME:-huly-elastic-logs}
  elastic-data:
    name: ${ELASTIC_DATA_NAME:-huly-elastic-data}
  elastic-conf:
    name: ${ELASTIC_CONF_NAME:-huly-elastic-conf}
  minio-data:
    name: ${MINIO_DATA_NAME:-huly-minio-data}
  workspace-logs:
    name: ${WORKSPACE_LOGS_NAME:-huly-workspace-logs}
  transactor-logs:
    name: ${TRANSACTOR_LOGS_NAME:-huly-transactor-logs}
  collaborator-logs:
    name: ${COLLABORATOR_LOGS_NAME:-huly-collaborator-logs}
  front-logs:
    name: ${FRONT_LOGS_NAME:-huly-front-logs}
  account-logs:
    name: ${ACCOUNT_LOGS_NAME:-huly-account-logs}