services:
  mongodb:
    image: mongo:${MONGODB_IMAGE_TAG:-7-jammy}
    container_name: ${MONGODB_CONTAINER_NAME:-mongodb}
    environment:
      - PUID=${MONGODB_PUID:-1000}
      - PGID=${MONGODB_PGID:-1000}
    volumes:
      - ${MONGODB_VOLUME:-/opt/docker/huly/mongodb}:/data/db
    restart: ${MONGODB_RESTART_POLICY:-unless-stopped}
    networks:
      - internal-services
    # TODO (dreamboat-dev) change log level

  # TODO (dreamboat-dev) check if postgres would work instead of mongodb
  # postgres:
  #   image: postgres:${PSOTGRES_IMAGE_TAG:-latest}
  #   container_name: ${POSTGRES_CONTAINER_NAME:-postgres}
  #   environment:
  #     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-example}
  #   volumes:
  #     - ${POSTGRES_VOLUME:-/opt/docker/huly/postgres}:/data/db
  #   restart: ${POSTGRES_RESTART_POLICY:-unless-stopped}

  elastic:
    image: elasticsearch:${ELASTIC_IMAGE_TAG:-7.14.2}
    # command: |
    #   /bin/sh -c "./bin/elasticsearch-plugin list | grep -q ingest-attachment || yes | ./bin/elasticsearch-plugin install --silent ingest-attachment;
    #   /usr/local/bin/docker-entrypoint.sh eswrapper"
    command: ["elasticsearch", "-Elogger.level=WARN"] # log level: TRACE | DEBUG | INFO | WARN | ERROR | FATAL
    volumes:
      - ${ELASTIC_VOLUME:-/opt/docker/huly/mongodb}:/var/lib/elasticsearch/data
    environment:
      - ELASTICSEARCH_PORT_NUMBER=${ELASTIC_PORT:-9200}
      - BITNAMI_DEBUG=${ELASTIC_BITNAMI_DEBUG:-true}
      - discovery.type=${ELASTIC_DISCOVERY_TYPE:-single-node}
      - ES_JAVA_OPTS=${ELASTIC_JAVA_OPTS:--Xms1024m -Xmx1024m}
      - http.cors.enabled=${ELASTIC_HTTP_CORS_ENABLED:-true}
      - http.cors.allow-origin=${ELASTIC_HTTP_CORS_ALLOW_ORIGIN:-http://localhost:8082}
    healthcheck:
      interval: 20s
      retries: 10
      test: curl -s http://localhost:9200/_cluster/health | grep -vq '"status":"red"'
    restart: ${ELASTIC_RESTART_POLICY:-unless-stopped}
    networks:
      - internal-services

  minio:
    image: minio/minio:${MINIO_IMAGE_TAG:-latest}
    command: server /data --address :9000 --console-address :9001
    volumes:
      - ${MINIO_VOLUME:-/opt/docker/huly/minio}:/data
    restart: ${MINIO_RESTART_POLICY:-unless-stopped}
    networks:
      - internal-services

  rekoni:
    image: hardcoreeng/rekoni-service:${HULY_VERSION}
    environment:
      - SECRET=${HULY_SECRET:?}
    deploy:
      resources:
        limits:
          memory: ${REKONI_MAX_MEMORY:-500M}
    restart: ${REKONI_RESTART_POLICY:-unless-stopped}
    networks:
      - internal-services
      - traefik-public

  transactor:
    image: hardcoreeng/transactor:${HULY_VERSION}
    environment:
      - SERVER_PORT=${TRANSACTOR_PORT:-3333}
      - SERVER_SECRET=${HULY_SECRET:-secret}
      - SERVER_CURSOR_MAXTIMEMS=${SERVER_CURSOR_MAXTIMEMS:-30000}
      - ELASTIC_URL=${ELASTIC_URL:-http://elastic:9200}
      - ELASTIC_INDEX_NAME=${ELASTIC_INDEX_NAME:-huly_storage_index}
      - MONGO_URL=${MONGODB_URL:-mongodb://mongodb:27017}
      - METRICS_CONSOLE=${TRANSACTOR_METRICS_CONSOLE:-false}
      - METRICS_FILE=${TRANSACTOR_METRICS_FILE:-metrics.txt}
      - MINIO_ENDPOINT=${MINIO_ENDPOINT:-minio}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY:-minioadmin}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY:-minioadmin}
      - REKONI_URL=${REKONI_URL:-http://rekoni:4004}
      - FRONT_URL=${FRONT_URL:-http://localhost:8087}
      - SERVER_PROVIDER=${TRANSACTOR_SERVER_PROVIDER:-wss}
      - ACCOUNTS_URL=${ACCOUNTS_URL:-http://account:3000}
      - LAST_NAME_FIRST=${HULY_LAST_NAME_FIRST:-true}
      - UPLOAD_URL=${UPLOAD_URL:-https://${SERVER_ADDRESS}/files}
    restart: ${TRANSACTOR_RESTART_POLICY:-unless-stopped}
    networks:
      - internal-services
      - traefik-public

  collaborator:
    image: hardcoreeng/collaborator:${HULY_VERSION}
    environment:
      - COLLABORATOR_PORT=${COLLABORATOR_PORT:-3078}
      - SECRET=${HULY_SECRET:-secret}
      - ACCOUNTS_URL=${ACCOUNTS_URL:-http://account:3000}
      - TRANSACTOR_URL=${TRANSACTOR_URL:-ws://transactor:3333}
      - UPLOAD_URL=${FRONT_UPLOAD_URL:-/files}
      - MONGO_URL=${MONGODB_URL:-mongodb://mongodb:27017}
      - MINIO_ENDPOINT=${MINIO_ENDPOINT:-minio}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY:-minioadmin}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY:-minioadmin}
    restart: ${COLLABORATOR_RESTART_POLICY:-unless-stopped}
    networks:
      - internal-services
      - traefik-public

  account:
    image: hardcoreeng/account:${HULY_VERSION}
    environment:
      - SERVER_PORT=${ACCOUNT_PORT:-3000}
      - SERVER_SECRET=${HULY_SECRET:?}
      - MONGO_URL=${MONGODB_URL:-mongodb://mongodb:27017}
      - TRANSACTOR_URL=${TRANSACTOR_URL:-ws://transactor:3333}
      - ENDPOINT_URL=${TRANSACTOR_ENDPOINT_URL:-wss://${SERVER_ADDRESS}:3333} # this is the transactor endpoint
      - MINIO_ENDPOINT=${MINIO_ENDPOINT:-minio}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY:-minioadmin}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY:-minioadmin}
      - FRONT_URL=${FRONT_URL_2:-http://front:8080}
      - INIT_WORKSPACE=${HULY_INIT_WORKSPACE:-demo-tracker}
      - MODEL_ENABLED=${ACCOUNT_MODEL_ENABLED:-*}
      - ACCOUNTS_URL=${ACCOUNTS_URL_2:-http://localhost:3000}
      - ACCOUNT_PORT=${ACCOUNT_PORT:-3000}
    restart: ${ACCOUNT_RESTART_POLICY:-unless-stopped}
    networks:
      - internal-services
      - traefik-public

  front:
    image: hardcoreeng/front:${HULY_VERSION}
    environment:
      - SERVER_PORT=${FRONT_PORT:-8080}
      - SERVER_SECRET=${HULY_SECRET:?}
      - ACCOUNTS_URL=${ACCOUNTS_URL_PUBLIC:-https://${SERVER_ADDRESS}/accounts}
      - REKONI_URL=${REKONI_URL_PUBLIC:-https://${SERVER_ADDRESS}/rekoni}
      - CALENDAR_URL=${CALENDAR_URL:-https://${SERVER_ADDRESS}:8095}
      - GMAIL_URL=${GMAIL_URL:-https://${SERVER_ADDRESS}:8088}
      - TELEGRAM_URL=${TELEGRAM_URL:-https://${SERVER_ADDRESS}:8086}
      - UPLOAD_URL=${FRONT_UPLOAD_URL:-/files}
      - TRANSACTOR_URL=${TRANSACTOR_URL:-wss://${SERVER_ADDRESS}:3333}
      - ELASTIC_URL=${ELASTIC_URL:-http://elastic:9200}
      - COLLABORATOR_URL=${COLLABORATOR_URL:-wss://${SERVER_ADDRESS}:3078}
      - COLLABORATOR_API_URL=${COLLABORATOR_API:-https://${SERVER_ADDRESS}:3078}
      - MINIO_ENDPOINT=${MINIO_ENDPOINT}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY:-minioadmin}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY:-minioadmin}
      - MONGO_URL=${MONGODB_URL:-mongodb://mongodb:27017}
      - TITLE=${HULY_TITLE:-Huly Self Host}
      - DEFAULT_LANGUAGE=${HULY_DEFAULT_LANGUAGE:-en}
      - LAST_NAME_FIRST=${HULY_LAST_NAME_FIRST:-true}
    restart: ${FRONT_RESTART_POLICY:-unless-stopped}
    networks:
      - internal-services
      - traefik-public

networks:
  traefik-public:
    name: traefik-public
  internal-services:
    name: internal-services