services:
  traefik:
    image: traefik:${VERSION:?}
    container_name: ${CONTAINER_NAME:-traefik}
    hostname: ${HOSTNAME:-traefik}
    restart: ${RESTART_POLICY:-unless-stopped}
    ports:
      - ${HTTP_PORT:-80}:80
      - ${DASHBOARD_PORT:-8080}:8080
    volumes:
      - ${VOLUME_BIND_PATH:?}:/etc/traefik
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - traefik-net

networks:
  traefik-net:
    driver: bridge
    name: ${TRAEFIK_NET:-traefik-net}