services:
  traefik:
    image: traefik:${IMAGE_TAG:?}
    container_name: traefik
    hostname: traefik
    restart: unless-stopped
    ports:
      - 80:80
      - 8080:8080
    volumes:
    # permissions in container for
    # uid: 0
    # gid: 0
    #
    # /etc/traefik:
    # rwxr-xr-x
    #   - user:  rwx -> read, write, execute -> 7
    #   - group: r-x -> read, execute -> 5
    #   - other: r-x -> read, execute -> 5
    #
    # fileConfig.yml & traefik.yml:
    # rw-r--r--
    #   - user:  rw- -> read, write -> 6
    #   - group: r-- -> read -> 4
    #   - other: r-- -> read -> 4
      - ${TRAEFIK_PATH}:/etc/traefik
      - ${TRAEFIK_FILECONFIG_YML_PATH:?}:/etc/traefik/fileConfig.yml:ro
      - ${TRAEFIK_TRAEFIK_YML_PATH:?}:/etc/traefik/traefik.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - traefik-net
    env_file:
      - ./.env

networks:
  traefik-net:
    driver: bridge
    name: ${TRAEFIK_NET:-traefik-net}