services:
  portainer:
    image: portainer/portainer-ce:${IMAGE_TAG:?}
    container_name: ${CONTAINER_NAME:-portainer}
    hostname: ${HOSTNAME:-portainer}
    restart: ${RESTART_POLICY:-unless-stopped}
    ports:
      - ${PORTAINER_PORT:-9443}:9443
    volumes:
      - ${PORTAINER_PATH:?}:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - portainer-net

networks:
  portainer-net:
    driver: bridge
    name: ${PORTAINER_NET:-portainer-net}